@baseUrl = http://localhost:7090/api/v1
@adminUsername = admin1
@adminPassword = admin12
@userUsername = user12
@userPassword = test12


### Create User - this one will only get a USER role by default
POST {{baseUrl}}/auth/register/

{
    "username": "user12",
    "password": "test12"
}

> {% client.global.set("token", response.body.token); %}

### USER login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "password": "{{userPassword}}"
}

> {% client.global.set("token", response.body.token); %}


### Create Admin user
POST {{baseUrl}}/auth/register/

{
    "username": "admin1",
    "password": "admin12"
}

> {% client.global.set("token", response.body.token); %}

### ADMIN login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {% client.global.set("token", response.body.token); %}

### Get all candidates
GET {{baseUrl}}/candidates
Authorization: Bearer {{token}}

### Get candidate by id
GET {{baseUrl}}/candidates/1
Authorization: Bearer {{token}}

### Create candidate
POST {{baseUrl}}/candidates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Peter",
  "phonenumber": "12345678"
}

### Update candidate
PUT {{baseUrl}}/candidates/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "phonenumber": "87654321"
}

### Delete candidate
DELETE {{baseUrl}}/candidates/1
Authorization: Bearer {{token}}

### Get all skills
GET {{baseUrl}}/skills
Authorization: Bearer {{token}}

### Get skill by id
GET {{baseUrl}}/skills/1
Authorization: Bearer {{token}}

### Create skill
POST {{baseUrl}}/skills
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "java",
  "category": "DB",
  "description": "Databases and data storage technologies"
}

### Update skill
PUT {{baseUrl}}/skills/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Application frameworks and libraries"
}

### Delete skill
DELETE {{baseUrl}}/skills/1
Authorization: Bearer {{token}}

### Add skill to candidate
PUT {{baseUrl}}/candidates/1/skills/1
Authorization: Bearer {{token}}

